// Renderers: a single Skill IR -> (1) a human/AI-readable Markdown skill doc,
// and (2) an executable Playwright spec. Both consume only the IR.

// --- (1) Markdown skill doc ------------------------------------------------

export function renderMarkdown(ir) {
  const params = ir.parameters.length
    ? ir.parameters.map((p) => `${p.name}`).join(', ')
    : '(无)';

  const lines = [];
  lines.push('---');
  lines.push(`name: ${ir.name}`);
  lines.push(`description: ${ir.description}`);
  lines.push(`parameters: [${params}]`);
  lines.push(`generated_by: ${ir.generatedBy}`);
  lines.push('---');
  lines.push('');
  lines.push(`## 起始页面`);
  lines.push(ir.startUrl || '(未知)');
  lines.push('');

  if (ir.parameters.length) {
    lines.push('## 参数');
    lines.push('| 名称 | 类型 | 示例 |');
    lines.push('| --- | --- | --- |');
    for (const p of ir.parameters) lines.push(`| ${p.name} | ${p.type} | ${truncate(p.example)} |`);
    lines.push('');
  }

  lines.push('## 步骤');
  let n = 0;
  for (const s of ir.steps) {
    if (s.kind === 'ui') {
      n += 1;
      const valuePart = s.value != null && s.action !== 'click' ? ` = \`${s.value}\`` : '';
      const labelPart = s.label ? `「${s.label}」` : `\`${s.selector}\``;
      lines.push(`${n}. **${actionLabel(s.action)}** ${labelPart}${valuePart}`);
    } else if (s.kind === 'api') {
      const ex = Object.keys(s.responseExtract || {});
      const exPart = ex.length ? ` → 提取 ${ex.join(', ')}` : '';
      lines.push(`   ↳ 触发 API: \`${s.method} ${s.urlPattern}\` (期望 ${s.expectStatus ?? '2xx'})${exPart}`);
    } else if (s.kind === 'nav') {
      if (s.url === ir.startUrl) continue; // already covered by 起始页面
      n += 1;
      lines.push(`${n}. 跳转到 \`${s.url}\``);
    }
  }
  lines.push('');

  const apis = ir.steps.filter((s) => s.kind === 'api');
  if (apis.length) {
    lines.push('## API 契约');
    for (const a of apis) {
      const body = a.requestKeys.length ? ` body: { ${a.requestKeys.join(', ')} }` : '';
      lines.push(`- \`${a.method} ${a.urlPattern}\`${body} → ${a.expectStatus ?? '2xx'}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function actionLabel(a) {
  return { click: '点击', type: '输入', select: '选择' }[a] || a;
}
function truncate(v, n = 40) {
  const s = String(v ?? '');
  return s.length > n ? s.slice(0, n) + '…' : s;
}

// --- (2) Playwright executable spec ----------------------------------------

export function renderPlaywright(ir) {
  const paramDefaults = ir.parameters
    .map((p) => `  ${p.name}: ${JSON.stringify(String(p.example ?? ''))},`)
    .join('\n');

  const body = [];
  for (const s of ir.steps) {
    if (s.kind === 'ui') {
      const sel = locatorFor(s);
      if (s.action === 'click') {
        body.push(`  await ${sel}.click();`);
      } else if (s.action === 'type') {
        body.push(`  await ${sel}.fill(${valueExpr(s.value)});`);
      } else if (s.action === 'select') {
        body.push(`  await ${sel}.selectOption(${valueExpr(s.value)});`);
      }
    } else if (s.kind === 'api') {
      body.push(
        `  // expected side-effect: ${s.method} ${s.urlPattern} -> ${s.expectStatus ?? '2xx'}`
      );
      if (s.expectStatus) {
        body.push(
          `  await page.waitForResponse(r => r.url().includes(${JSON.stringify(
            pathOnly(s.urlPattern)
          )}) && r.status() === ${s.expectStatus}).catch(() => {});`
        );
      }
    } else if (s.kind === 'nav') {
      if (s.url === ir.startUrl) continue; // page.goto(startUrl) already emitted
      body.push(`  await page.goto(${JSON.stringify(s.url)});`);
    }
  }

  return `// Auto-generated Playwright spec for skill: ${ir.name}
// Generated by: ${ir.generatedBy}
// Run:  npx playwright test ${ir.slug}.spec.ts
import { test, expect } from '@playwright/test';

const params = {
${paramDefaults}
};

test(${JSON.stringify(ir.name)}, async ({ page }) => {
  await page.goto(${JSON.stringify(ir.startUrl || 'about:blank')});
${body.join('\n')}
});
`;
}

function locatorFor(s) {
  // Prefer a stable role/text locator; fall back to the raw CSS selector.
  if (s.label && s.action === 'click') {
    return `page.getByText(${JSON.stringify(s.label)}, { exact: false }).first()`;
  }
  return `page.locator(${JSON.stringify(s.selector)})`;
}

function valueExpr(value) {
  // `{paramName}` -> params.paramName ; otherwise a string literal.
  const m = typeof value === 'string' && value.match(/^\{(.+)\}$/);
  return m ? `params.${m[1]}` : JSON.stringify(String(value ?? ''));
}

function pathOnly(pattern) {
  return pattern.split('?')[0];
}
